---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ylrdxapi/RVHSGAMEJAM2024
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp -R static $DEPLOYPATH
    - /bin/cp -R templates $DEPLOYPATH
    - /bin/cp -R backend $DEPLOYPATH